/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.LayoutManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import task_manager.InterfaceManager;

/**
 *
 * @author gugag
 */

public class tela_principal extends javax.swing.JFrame {

    private InterfaceManager interfaceMng;
    
    public tela_principal(InterfaceManager newInterfaceMng) {
        
        interfaceMng = newInterfaceMng;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        excluirCard1 = new javax.swing.JPopupMenu();
        itemExcluir = new javax.swing.JMenuItem();
        excluirCard2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        excluirCard3 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        excluirCard4 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        excluirCard5 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        PainelMain = new javax.swing.JPanel();
        jpSideBar = new javax.swing.JPanel();
        logoSTOQ = new javax.swing.JLabel();
        labelSTOQ = new javax.swing.JLabel();
        jpOpcoes = new javax.swing.JPanel();
        jpClientes = new javax.swing.JPanel();
        iconeClientes = new javax.swing.JLabel();
        labelClientes = new javax.swing.JLabel();
        jpProdutos = new javax.swing.JPanel();
        iconeProdutos = new javax.swing.JLabel();
        labelProdutos = new javax.swing.JLabel();
        jpVendas = new javax.swing.JPanel();
        iconeVendas = new javax.swing.JLabel();
        labelVendas = new javax.swing.JLabel();
        jpPedidos = new javax.swing.JPanel();
        iconePedidos = new javax.swing.JLabel();
        labelPedidos = new javax.swing.JLabel();
        jpInventario = new javax.swing.JPanel();
        iconeInventario = new javax.swing.JLabel();
        labelInventario = new javax.swing.JLabel();
        jpBody = new javax.swing.JPanel();
        cardInventario = new javax.swing.JPanel();
        mensagemCard1 = new javax.swing.JLabel();
        tabelaCard1 = new javax.swing.JScrollPane();
        jtCard1 = new javax.swing.JTable();
        cadastrarCard1 = new javax.swing.JButton();
        buscarCard1 = new javax.swing.JButton();
        cardPedidos = new javax.swing.JPanel();
        tabelaCard2 = new javax.swing.JScrollPane();
        jtCard2 = new javax.swing.JTable();
        mensagemCard2 = new javax.swing.JLabel();
        cadastrarCard2 = new javax.swing.JButton();
        buscarCard2 = new javax.swing.JButton();
        cardVendas = new javax.swing.JPanel();
        tabelaCard3 = new javax.swing.JScrollPane();
        jtCard3 = new javax.swing.JTable();
        mensagemCard3 = new javax.swing.JLabel();
        cadastrarCard3 = new javax.swing.JButton();
        buscarCard3 = new javax.swing.JButton();
        cardProdutos = new javax.swing.JPanel();
        tabelaCard4 = new javax.swing.JScrollPane();
        jtCard4 = new javax.swing.JTable();
        mensagemCard4 = new javax.swing.JLabel();
        cadastrarCard4 = new javax.swing.JButton();
        buscarCard4 = new javax.swing.JButton();
        cardClientes = new javax.swing.JPanel();
        tabelaCard5 = new javax.swing.JScrollPane();
        jtCard5 = new javax.swing.JTable();
        mensagemCard5 = new javax.swing.JLabel();
        cadastrarCard5 = new javax.swing.JButton();
        buscarCard5 = new javax.swing.JButton();

        itemExcluir.setText("Excluir");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        excluirCard1.add(itemExcluir);

        jMenuItem1.setText("Excluir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        excluirCard2.add(jMenuItem1);

        jMenuItem2.setText("Excluir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        excluirCard3.add(jMenuItem2);

        jMenuItem3.setText("Excluir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        excluirCard4.add(jMenuItem3);

        jMenuItem4.setText("Excluir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        excluirCard5.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        PainelMain.setBackground(new java.awt.Color(255, 255, 255));
        PainelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSideBar.setBackground(new java.awt.Color(46, 0, 71));

        logoSTOQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/STOQ.png"))); // NOI18N

        labelSTOQ.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelSTOQ.setForeground(new java.awt.Color(0, 255, 255));
        labelSTOQ.setText("STOQ");

        jpOpcoes.setBackground(new java.awt.Color(72, 0, 112));
        jpOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpClientes.setBackground(new java.awt.Color(72, 0, 112));
        jpClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpClientes.setOpaque(false);
        jpClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpClientesMouseClicked(evt);
            }
        });

        iconeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/cliente.png"))); // NOI18N

        labelClientes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelClientes.setForeground(new java.awt.Color(0, 255, 255));
        labelClientes.setText("Clientes");

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconeClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(labelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpOpcoes.add(jpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 50));

        jpProdutos.setBackground(new java.awt.Color(72, 0, 112));
        jpProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpProdutos.setOpaque(false);
        jpProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpProdutosMouseClicked(evt);
            }
        });

        iconeProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/produtos.png"))); // NOI18N

        labelProdutos.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelProdutos.setForeground(new java.awt.Color(0, 255, 255));
        labelProdutos.setText("Produtos");

        javax.swing.GroupLayout jpProdutosLayout = new javax.swing.GroupLayout(jpProdutos);
        jpProdutos.setLayout(jpProdutosLayout);
        jpProdutosLayout.setHorizontalGroup(
            jpProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconeProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpProdutosLayout.setVerticalGroup(
            jpProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpOpcoes.add(jpProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 50));

        jpVendas.setBackground(new java.awt.Color(72, 0, 112));
        jpVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVendas.setOpaque(false);
        jpVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpVendasMouseClicked(evt);
            }
        });

        iconeVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/vendas.png"))); // NOI18N

        labelVendas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelVendas.setForeground(new java.awt.Color(0, 255, 255));
        labelVendas.setText("Vendas");

        javax.swing.GroupLayout jpVendasLayout = new javax.swing.GroupLayout(jpVendas);
        jpVendas.setLayout(jpVendasLayout);
        jpVendasLayout.setHorizontalGroup(
            jpVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconeVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpVendasLayout.setVerticalGroup(
            jpVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(labelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpOpcoes.add(jpVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 50));

        jpPedidos.setBackground(new java.awt.Color(72, 0, 112));
        jpPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpPedidos.setOpaque(false);
        jpPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPedidosMouseClicked(evt);
            }
        });

        iconePedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/pedidos.png"))); // NOI18N

        labelPedidos.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelPedidos.setForeground(new java.awt.Color(0, 255, 255));
        labelPedidos.setText("Pedidos");

        javax.swing.GroupLayout jpPedidosLayout = new javax.swing.GroupLayout(jpPedidos);
        jpPedidos.setLayout(jpPedidosLayout);
        jpPedidosLayout.setHorizontalGroup(
            jpPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPedidosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconePedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPedidosLayout.setVerticalGroup(
            jpPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconePedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(labelPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpOpcoes.add(jpPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 50));

        jpInventario.setBackground(new java.awt.Color(118, 0, 183));
        jpInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpInventarioMouseClicked(evt);
            }
        });

        iconeInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/inventario.png"))); // NOI18N

        labelInventario.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelInventario.setForeground(new java.awt.Color(0, 255, 255));
        labelInventario.setText("Inventário");

        javax.swing.GroupLayout jpInventarioLayout = new javax.swing.GroupLayout(jpInventario);
        jpInventario.setLayout(jpInventarioLayout);
        jpInventarioLayout.setHorizontalGroup(
            jpInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInventarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconeInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpInventarioLayout.setVerticalGroup(
            jpInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpInventarioLayout.createSequentialGroup()
                        .addComponent(labelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpOpcoes.add(jpInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 60));

        javax.swing.GroupLayout jpSideBarLayout = new javax.swing.GroupLayout(jpSideBar);
        jpSideBar.setLayout(jpSideBarLayout);
        jpSideBarLayout.setHorizontalGroup(
            jpSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpSideBarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelSTOQ)
                    .addComponent(logoSTOQ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSideBarLayout.setVerticalGroup(
            jpSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSideBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoSTOQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSTOQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelMain.add(jpSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 500));

        jpBody.setBackground(new java.awt.Color(0, 0, 255));
        jpBody.setLayout(new java.awt.CardLayout());

        cardInventario.setBackground(new java.awt.Color(255, 255, 255));

        mensagemCard1.setBackground(new java.awt.Color(46, 0, 71));
        mensagemCard1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mensagemCard1.setForeground(new java.awt.Color(46, 0, 71));
        mensagemCard1.setText("Olá, Bem-vindo ao seu inventário.");

        jtCard1.setBackground(new java.awt.Color(46, 0, 71));
        jtCard1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtCard1.setForeground(new java.awt.Color(0, 255, 255));
        jtCard1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Material", "Categoria", "Quantidade em Estoque", "Data da Última Compra", "Valor do Material", "Forncedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCard1.setComponentPopupMenu(excluirCard1);
        jtCard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaCard1.setViewportView(jtCard1);

        cadastrarCard1.setBackground(new java.awt.Color(118, 0, 183));
        cadastrarCard1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCard1.setForeground(new java.awt.Color(0, 255, 255));
        cadastrarCard1.setText("Cadastrar Material");
        cadastrarCard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCard1ActionPerformed(evt);
            }
        });

        buscarCard1.setBackground(new java.awt.Color(118, 0, 183));
        buscarCard1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarCard1.setForeground(new java.awt.Color(0, 255, 255));
        buscarCard1.setText("Buscar Material");
        buscarCard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCard1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardInventarioLayout = new javax.swing.GroupLayout(cardInventario);
        cardInventario.setLayout(cardInventarioLayout);
        cardInventarioLayout.setHorizontalGroup(
            cardInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardInventarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(cardInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(cardInventarioLayout.createSequentialGroup()
                            .addComponent(buscarCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(cadastrarCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tabelaCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mensagemCard1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        cardInventarioLayout.setVerticalGroup(
            cardInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardInventarioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mensagemCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpBody.add(cardInventario, "card1");

        cardPedidos.setBackground(new java.awt.Color(255, 255, 255));

        jtCard2.setBackground(new java.awt.Color(46, 0, 71));
        jtCard2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtCard2.setForeground(new java.awt.Color(0, 255, 255));
        jtCard2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID de pedido", "Nome do Cliente", "Data do Pedido", "Produtos Vendidos", "Valor Total", "Forma de Pagamento", "Desconto Aplicado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCard2.setViewportView(jtCard2);

        mensagemCard2.setBackground(new java.awt.Color(46, 0, 71));
        mensagemCard2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mensagemCard2.setForeground(new java.awt.Color(46, 0, 71));
        mensagemCard2.setText("Seção de Pedidos");

        cadastrarCard2.setBackground(new java.awt.Color(118, 0, 183));
        cadastrarCard2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCard2.setForeground(new java.awt.Color(0, 255, 255));
        cadastrarCard2.setText("Cadastrar Pedido");
        cadastrarCard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCard2ActionPerformed(evt);
            }
        });

        buscarCard2.setBackground(new java.awt.Color(118, 0, 183));
        buscarCard2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarCard2.setForeground(new java.awt.Color(0, 255, 255));
        buscarCard2.setText("Buscar Pedido");
        buscarCard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCard2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardPedidosLayout = new javax.swing.GroupLayout(cardPedidos);
        cardPedidos.setLayout(cardPedidosLayout);
        cardPedidosLayout.setHorizontalGroup(
            cardPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPedidosLayout.createSequentialGroup()
                .addGap(16, 19, Short.MAX_VALUE)
                .addGroup(cardPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(cardPedidosLayout.createSequentialGroup()
                        .addComponent(buscarCard2)
                        .addGap(15, 15, 15)
                        .addComponent(cadastrarCard2))
                    .addComponent(tabelaCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(cardPedidosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mensagemCard2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPedidosLayout.setVerticalGroup(
            cardPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPedidosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mensagemCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaCard2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(cardPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jpBody.add(cardPedidos, "card2");

        cardVendas.setBackground(new java.awt.Color(255, 255, 255));

        jtCard3.setBackground(new java.awt.Color(46, 0, 71));
        jtCard3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtCard3.setForeground(new java.awt.Color(0, 255, 255));
        jtCard3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID de Venda", "Nome do Cliente", "Data de Venda", "Produtos Vendidos", "Valor Total", "Foma de Pagamento", "Desconto Aplicado:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCard3.setViewportView(jtCard3);

        mensagemCard3.setBackground(new java.awt.Color(46, 0, 71));
        mensagemCard3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mensagemCard3.setForeground(new java.awt.Color(46, 0, 71));
        mensagemCard3.setText("Seção de Vendas Realizadas");

        cadastrarCard3.setBackground(new java.awt.Color(118, 0, 183));
        cadastrarCard3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCard3.setForeground(new java.awt.Color(0, 255, 255));
        cadastrarCard3.setText("Cadastrar Venda");
        cadastrarCard3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCard3ActionPerformed(evt);
            }
        });

        buscarCard3.setBackground(new java.awt.Color(118, 0, 183));
        buscarCard3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarCard3.setForeground(new java.awt.Color(0, 255, 255));
        buscarCard3.setText("Buscar Venda");
        buscarCard3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCard3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardVendasLayout = new javax.swing.GroupLayout(cardVendas);
        cardVendas.setLayout(cardVendasLayout);
        cardVendasLayout.setHorizontalGroup(
            cardVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardVendasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(cardVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(cardVendasLayout.createSequentialGroup()
                            .addComponent(buscarCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(cadastrarCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tabelaCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mensagemCard3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        cardVendasLayout.setVerticalGroup(
            cardVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardVendasLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mensagemCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpBody.add(cardVendas, "card3");

        cardProdutos.setBackground(new java.awt.Color(255, 255, 255));

        jtCard4.setBackground(new java.awt.Color(46, 0, 71));
        jtCard4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtCard4.setForeground(new java.awt.Color(0, 255, 255));
        jtCard4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Categoria", "Valor do Material", "Valor de Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCard4.setViewportView(jtCard4);

        mensagemCard4.setBackground(new java.awt.Color(46, 0, 71));
        mensagemCard4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mensagemCard4.setForeground(new java.awt.Color(46, 0, 71));
        mensagemCard4.setText("Seção de Produtos");

        cadastrarCard4.setBackground(new java.awt.Color(118, 0, 183));
        cadastrarCard4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCard4.setForeground(new java.awt.Color(0, 255, 255));
        cadastrarCard4.setText("Cadastrar Produto");
        cadastrarCard4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCard4ActionPerformed(evt);
            }
        });

        buscarCard4.setBackground(new java.awt.Color(118, 0, 183));
        buscarCard4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarCard4.setForeground(new java.awt.Color(0, 255, 255));
        buscarCard4.setText("Buscar Produto");
        buscarCard4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCard4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardProdutosLayout = new javax.swing.GroupLayout(cardProdutos);
        cardProdutos.setLayout(cardProdutosLayout);
        cardProdutosLayout.setHorizontalGroup(
            cardProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProdutosLayout.createSequentialGroup()
                .addGap(16, 170, Short.MAX_VALUE)
                .addComponent(buscarCard4)
                .addGap(36, 36, 36)
                .addComponent(cadastrarCard4)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(cardProdutosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cardProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaCard4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensagemCard4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardProdutosLayout.setVerticalGroup(
            cardProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProdutosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mensagemCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpBody.add(cardProdutos, "card4");

        cardClientes.setBackground(new java.awt.Color(255, 255, 255));

        jtCard5.setBackground(new java.awt.Color(46, 0, 71));
        jtCard5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtCard5.setForeground(new java.awt.Color(0, 255, 255));
        jtCard5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Número", "Quantidade Compras", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCard5.setViewportView(jtCard5);

        mensagemCard5.setBackground(new java.awt.Color(46, 0, 71));
        mensagemCard5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mensagemCard5.setForeground(new java.awt.Color(46, 0, 71));
        mensagemCard5.setText("Seção de Clientes");

        cadastrarCard5.setBackground(new java.awt.Color(118, 0, 183));
        cadastrarCard5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCard5.setForeground(new java.awt.Color(0, 255, 255));
        cadastrarCard5.setText("Cadastrar Cliente");
        cadastrarCard5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCard5ActionPerformed(evt);
            }
        });

        buscarCard5.setBackground(new java.awt.Color(118, 0, 183));
        buscarCard5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarCard5.setForeground(new java.awt.Color(0, 255, 255));
        buscarCard5.setText("Buscar Cliente");
        buscarCard5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCard5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardClientesLayout = new javax.swing.GroupLayout(cardClientes);
        cardClientes.setLayout(cardClientesLayout);
        cardClientesLayout.setHorizontalGroup(
            cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardClientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(tabelaCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cardClientesLayout.createSequentialGroup()
                            .addComponent(buscarCard5)
                            .addGap(21, 21, 21)
                            .addComponent(cadastrarCard5)))
                    .addComponent(mensagemCard5))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        cardClientesLayout.setVerticalGroup(
            cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardClientesLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mensagemCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaCard5, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jpBody.add(cardClientes, "card5");

        PainelMain.add(jpBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 690, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInventarioMouseClicked
        jpInventario.setOpaque(true);
        jpInventario.setBackground(new Color(118,0,183));
        resetColor(new JPanel[]{jpClientes,jpPedidos,jpProdutos,jpVendas});
        
        cardInventario.show(true);
        resetCards(new JPanel[]{cardProdutos,cardPedidos,cardVendas,cardClientes});
    }//GEN-LAST:event_jpInventarioMouseClicked

    private void jpPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPedidosMouseClicked
        jpPedidos.setOpaque(true);
        jpPedidos.setBackground(new Color(118,0,183));
        resetColor(new JPanel[]{jpClientes,jpInventario,jpProdutos,jpVendas});
        
        cardPedidos.show(true);
        resetCards(new JPanel[]{cardProdutos,cardVendas,cardInventario,cardClientes});
    }//GEN-LAST:event_jpPedidosMouseClicked

    private void jpVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVendasMouseClicked
        jpVendas.setOpaque(true);
        jpVendas.setBackground(new Color(118,0,183));
        resetColor(new JPanel[]{jpClientes,jpPedidos,jpProdutos,jpInventario});
        
        cardVendas.show(true);
        resetCards(new JPanel[]{cardProdutos,cardPedidos,cardInventario,cardClientes});
    }//GEN-LAST:event_jpVendasMouseClicked

    private void jpProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpProdutosMouseClicked
        jpProdutos.setOpaque(true);
        jpProdutos.setBackground(new Color(118,0,183));
        resetColor(new JPanel[]{jpClientes,jpPedidos,jpInventario,jpVendas});
        
        cardProdutos.show(true);
        resetCards(new JPanel[]{cardClientes,cardPedidos,cardInventario,cardVendas});
    }//GEN-LAST:event_jpProdutosMouseClicked

    private void jpClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpClientesMouseClicked
        jpClientes.setOpaque(true);
        jpClientes.setBackground(new Color(118,0,183));
        resetColor(new JPanel[]{jpProdutos,jpPedidos,jpInventario,jpVendas});
        
        cardClientes.show(true);
        resetCards(new JPanel[]{cardProdutos,cardPedidos,cardInventario,cardVendas});
    }//GEN-LAST:event_jpClientesMouseClicked

    private void cadastrarCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCard1ActionPerformed
        
//        JDialog tela_cadastro = new tela_cadastroDados(this, true);
//        tela_cadastro.setVisible(true);
//        
//        CardLayout c1 = (CardLayout) tela_cadastro.getLayout();
//        c1.show(tela_cadastro,"card4");

//        A função acima foi uma tentativa de fazer um unico JDialog com layout de cartão para instanciar apenas uma janela,
//        porém não consegui, devido isso, optei por fazer varias telas de cadastro separadamente

          
            interfaceMng.abrirTelaCadastroMaterial();
            
        
    }//GEN-LAST:event_cadastrarCard1ActionPerformed

    private void cadastrarCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCard2ActionPerformed
        
            interfaceMng.abrirTelaCadastroPedido();
         
    }//GEN-LAST:event_cadastrarCard2ActionPerformed

    private void cadastrarCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCard3ActionPerformed
       
            interfaceMng.abrirTelaCadastroVenda();
        
    }//GEN-LAST:event_cadastrarCard3ActionPerformed

    private void cadastrarCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCard4ActionPerformed
        
            interfaceMng.abrirTelaCadastroProduto();
        
    }//GEN-LAST:event_cadastrarCard4ActionPerformed

    private void cadastrarCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCard5ActionPerformed
        
            interfaceMng.abrirTelaCadastroCliente();
    }//GEN-LAST:event_cadastrarCard5ActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        
        int linha = jtCard1.getSelectedRow();
        
        if(linha >= 0){
            ((DefaultTableModel) jtCard1.getModel()).removeRow(linha);
        }
    }//GEN-LAST:event_itemExcluirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        int linha = jtCard2.getSelectedRow();
        
        if(linha >= 0){
            ((DefaultTableModel) jtCard2.getModel()).removeRow(linha);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        int linha = jtCard3.getSelectedRow();
        
        if(linha >= 0){
            ((DefaultTableModel) jtCard3.getModel()).removeRow(linha);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        int linha = jtCard1.getSelectedRow();
        
        if(linha >= 0){
            ((DefaultTableModel) jtCard1.getModel()).removeRow(linha);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        int linha = jtCard1.getSelectedRow();
        
        if(linha >= 0){
            ((DefaultTableModel) jtCard1.getModel()).removeRow(linha);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void buscarCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCard5ActionPerformed
        
        interfaceMng.abrirTelaBuscarCliente();
     
    }//GEN-LAST:event_buscarCard5ActionPerformed

    private void buscarCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCard4ActionPerformed
        
        interfaceMng.abrirTelaBuscarProduto();
    }//GEN-LAST:event_buscarCard4ActionPerformed

    private void buscarCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCard3ActionPerformed
        
        interfaceMng.abrirTelaBuscarCliente();
    }//GEN-LAST:event_buscarCard3ActionPerformed

    private void buscarCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCard2ActionPerformed
        
       interfaceMng.abrirTelaBuscarCliente();
    }//GEN-LAST:event_buscarCard2ActionPerformed

    private void buscarCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCard1ActionPerformed
        
        interfaceMng.abrirTelaBuscarMaterial();
    }//GEN-LAST:event_buscarCard1ActionPerformed


    /**
     * @param args the command line arguments
     */
    
    
private void resetColor(JPanel [] pane){
    
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(72,0,112));
           pane[i].setOpaque(false);
        }
        
}

private void resetCards(JPanel [] pane){
    
        for(int i=0;i<pane.length;i++){
           pane[i].show(false);
        }
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMain;
    private javax.swing.JButton buscarCard1;
    private javax.swing.JButton buscarCard2;
    private javax.swing.JButton buscarCard3;
    private javax.swing.JButton buscarCard4;
    private javax.swing.JButton buscarCard5;
    private javax.swing.JButton cadastrarCard1;
    private javax.swing.JButton cadastrarCard2;
    private javax.swing.JButton cadastrarCard3;
    private javax.swing.JButton cadastrarCard4;
    private javax.swing.JButton cadastrarCard5;
    private javax.swing.JPanel cardClientes;
    private javax.swing.JPanel cardInventario;
    private javax.swing.JPanel cardPedidos;
    private javax.swing.JPanel cardProdutos;
    private javax.swing.JPanel cardVendas;
    private javax.swing.JPopupMenu excluirCard1;
    private javax.swing.JPopupMenu excluirCard2;
    private javax.swing.JPopupMenu excluirCard3;
    private javax.swing.JPopupMenu excluirCard4;
    private javax.swing.JPopupMenu excluirCard5;
    private javax.swing.JLabel iconeClientes;
    private javax.swing.JLabel iconeInventario;
    private javax.swing.JLabel iconePedidos;
    private javax.swing.JLabel iconeProdutos;
    private javax.swing.JLabel iconeVendas;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpInventario;
    private javax.swing.JPanel jpOpcoes;
    private javax.swing.JPanel jpPedidos;
    private javax.swing.JPanel jpProdutos;
    private javax.swing.JPanel jpSideBar;
    private javax.swing.JPanel jpVendas;
    private javax.swing.JTable jtCard1;
    private javax.swing.JTable jtCard2;
    private javax.swing.JTable jtCard3;
    private javax.swing.JTable jtCard4;
    private javax.swing.JTable jtCard5;
    private javax.swing.JLabel labelClientes;
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelPedidos;
    private javax.swing.JLabel labelProdutos;
    private javax.swing.JLabel labelSTOQ;
    private javax.swing.JLabel labelVendas;
    private javax.swing.JLabel logoSTOQ;
    private javax.swing.JLabel mensagemCard1;
    private javax.swing.JLabel mensagemCard2;
    private javax.swing.JLabel mensagemCard3;
    private javax.swing.JLabel mensagemCard4;
    private javax.swing.JLabel mensagemCard5;
    private javax.swing.JScrollPane tabelaCard1;
    private javax.swing.JScrollPane tabelaCard2;
    private javax.swing.JScrollPane tabelaCard3;
    private javax.swing.JScrollPane tabelaCard4;
    private javax.swing.JScrollPane tabelaCard5;
    // End of variables declaration//GEN-END:variables
}
