/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import static funcoesUteis.FuncoesDate.strToDate;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import task_manager.InterfaceManager;

/**
 *
 * @author gugag
 */
public class tela_cadastroProduto extends javax.swing.JDialog {

    private InterfaceManager ger;
    
    public tela_cadastroProduto(java.awt.Frame parent, boolean modal, InterfaceManager ger) {
        super(parent, modal);
        this.ger = ger;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCategoria = new javax.swing.ButtonGroup();
        jpMain = new javax.swing.JPanel();
        labelCabecalho = new javax.swing.JLabel();
        labelIcone = new javax.swing.JLabel();
        labelProduto = new javax.swing.JLabel();
        campoNomeProduto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        botaoCadastrar = new javax.swing.JButton();
        labelValorFinal = new javax.swing.JLabel();
        campoValorFinal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        opcaoPersonalizado = new javax.swing.JRadioButton();
        opcaoBordado = new javax.swing.JRadioButton();
        opcaoOutros = new javax.swing.JRadioButton();
        labelEspecifique = new javax.swing.JLabel();
        campoEspecifique = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoLista = new javax.swing.JList<>();
        campoValorMaterial = new javax.swing.JFormattedTextField();
        labelValorMaterial = new javax.swing.JLabel();
        botaoPesquisar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoCadastrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jpMain.setBackground(new java.awt.Color(46, 0, 71));

        labelCabecalho.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCabecalho.setForeground(new java.awt.Color(0, 255, 255));
        labelCabecalho.setText("Cadastro de Produto");

        labelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/icons8_logout_rounded_left_32px.png"))); // NOI18N
        labelIcone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIcone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIconeMouseClicked(evt);
            }
        });

        labelProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProduto.setForeground(new java.awt.Color(147, 0, 255));
        labelProduto.setText("Nome do Produto:");

        campoNomeProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        campoNomeProduto.setForeground(new java.awt.Color(46, 0, 71));

        jSeparator4.setBackground(new java.awt.Color(0, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 255, 255));

        botaoCadastrar.setBackground(new java.awt.Color(0, 255, 255));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(46, 0, 71));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        labelValorFinal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelValorFinal.setForeground(new java.awt.Color(147, 0, 255));
        labelValorFinal.setText("Valor final do Produto:");

        campoValorFinal.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoValorFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoValorFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorFinalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(147, 0, 255));
        jLabel1.setText("Material Utilizado:");

        jPanel1.setBackground(new java.awt.Color(46, 0, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 0, 255), 2, true), "Categoria", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(147, 0, 255));

        opcaoPersonalizado.setBackground(new java.awt.Color(46, 0, 71));
        grupoCategoria.add(opcaoPersonalizado);
        opcaoPersonalizado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoPersonalizado.setForeground(new java.awt.Color(147, 0, 255));
        opcaoPersonalizado.setMnemonic('P');
        opcaoPersonalizado.setSelected(true);
        opcaoPersonalizado.setText("Personalizado Digital");
        opcaoPersonalizado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcaoPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoPersonalizadoActionPerformed(evt);
            }
        });

        opcaoBordado.setBackground(new java.awt.Color(46, 0, 71));
        grupoCategoria.add(opcaoBordado);
        opcaoBordado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoBordado.setForeground(new java.awt.Color(147, 0, 255));
        opcaoBordado.setMnemonic('B');
        opcaoBordado.setText("Bordado");
        opcaoBordado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcaoBordado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoBordadoActionPerformed(evt);
            }
        });

        opcaoOutros.setBackground(new java.awt.Color(46, 0, 71));
        grupoCategoria.add(opcaoOutros);
        opcaoOutros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        opcaoOutros.setForeground(new java.awt.Color(147, 0, 255));
        opcaoOutros.setMnemonic('O');
        opcaoOutros.setText("Outros");
        opcaoOutros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcaoOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoOutrosActionPerformed(evt);
            }
        });

        labelEspecifique.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEspecifique.setForeground(new java.awt.Color(147, 0, 255));
        labelEspecifique.setText("Especifique:");
        labelEspecifique.setEnabled(false);

        campoEspecifique.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoEspecifique)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEspecifique)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(opcaoBordado)
                                .addGap(18, 18, 18)
                                .addComponent(opcaoPersonalizado)
                                .addGap(18, 18, 18)
                                .addComponent(opcaoOutros)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcaoBordado)
                    .addComponent(opcaoPersonalizado)
                    .addComponent(opcaoOutros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEspecifique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEspecifique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 0, 71));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 0, 255), 2, true), "Material Utilizado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(147, 0, 255));

        campoLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        campoLista.setForeground(new java.awt.Color(46, 0, 71));
        campoLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        campoLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(campoLista);

        campoValorMaterial.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoValorMaterial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoValorMaterial.setEnabled(false);

        labelValorMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelValorMaterial.setForeground(new java.awt.Color(147, 0, 255));
        labelValorMaterial.setText("Valor do material utilizado:");

        botaoPesquisar.setBackground(new java.awt.Color(0, 255, 255));
        botaoPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoPesquisar.setForeground(new java.awt.Color(46, 0, 71));
        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoLimpar.setBackground(new java.awt.Color(0, 255, 255));
        botaoLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoLimpar.setForeground(new java.awt.Color(46, 0, 71));
        botaoLimpar.setText("Limpar");
        botaoLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValorMaterial)
                    .addComponent(campoValorMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoLimpar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelValorMaterial)
                .addGap(6, 6, 6)
                .addComponent(campoValorMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botaoCadastrar1.setBackground(new java.awt.Color(0, 255, 255));
        botaoCadastrar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoCadastrar1.setForeground(new java.awt.Color(46, 0, 71));
        botaoCadastrar1.setText("Limpar Campos");
        botaoCadastrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNomeProduto)
                            .addComponent(labelProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValorFinal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoValorFinal))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator4)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelIcone)
                .addGap(8, 8, 8)
                .addComponent(labelCabecalho)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastrar1)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcone)
                    .addComponent(labelCabecalho))
                .addGap(12, 12, 12)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelProduto)
                .addGap(6, 6, 6)
                .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelValorFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoValorFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorFinalActionPerformed
        
        
    }//GEN-LAST:event_campoValorFinalActionPerformed

    private void labelIconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIconeMouseClicked

        this.setVisible(false);
    }//GEN-LAST:event_labelIconeMouseClicked

    private void opcaoOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoOutrosActionPerformed
        
        labelEspecifique.setEnabled(true);
        campoEspecifique.setEnabled(true);
    }//GEN-LAST:event_opcaoOutrosActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        String msgErro = "";
        msgErro = validarCampos(msgErro);
        
        if(msgErro.isEmpty()){
            
            String nomeProduto = campoNomeProduto.getText();
            
            String categoria;
            
            if(grupoCategoria.getSelection().getMnemonic() == 'B')
                categoria = "Bordado";
            else if(grupoCategoria.getSelection().getMnemonic() == 'P')
                categoria = "Personalizado Digital";
            else
                categoria = campoEspecifique.getText();
            
            List<String> listaMateriais = campoLista.getSelectedValuesList();
            
            //formatação do campo "Valor Final do Produto"
                String valorFnl = campoValorFinal.getText();

                valorFnl = valorFnl.replace(",", "");

                for(int i=0; i<valorFnl.length();i++)
                    valorFnl = valorFnl.replace(" ", "");
            
                Double valorFinal = Double.parseDouble(valorFnl);
            
        }else
            JOptionPane.showMessageDialog(this, msgErro, "Erro de Cadastro - Cliente", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        
        ger.abrirTelaBuscarProduto();
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        
        int[] indices = {};
        campoLista.setSelectedIndices(indices);
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void opcaoPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoPersonalizadoActionPerformed
        
        labelEspecifique.setEnabled(false);
        campoEspecifique.setEnabled(false);
    }//GEN-LAST:event_opcaoPersonalizadoActionPerformed

    private void opcaoBordadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoBordadoActionPerformed
        
        labelEspecifique.setEnabled(false);
        campoEspecifique.setEnabled(false);
    }//GEN-LAST:event_opcaoBordadoActionPerformed

    private void botaoCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrar1ActionPerformed
        
        campoNomeProduto.setText("");
        opcaoPersonalizado.setSelected(true);
        labelEspecifique.setEnabled(false);
        campoEspecifique.setEnabled(false);
        campoEspecifique.setText("");
        int[] indices = {};
        campoLista.setSelectedIndices(indices);
        campoValorFinal.setText("");
    }//GEN-LAST:event_botaoCadastrar1ActionPerformed

    public String validarCampos(String msgErro){
        
        if(campoNomeProduto.getText().isEmpty()){
            msgErro = msgErro + "Nome inválido!\n";
            campoNomeProduto.setForeground(Color.red);
            campoNomeProduto.setText("");
        }else
            campoNomeProduto.setForeground(new Color(46,0,71));
        
        if(campoLista.getSelectedValuesList().isEmpty()){
            msgErro = msgErro + "Selecione pelo menos 1 material!\n";
            campoLista.setForeground(Color.red);
        }else
            campoLista.setForeground(new Color(46,0,71));
        
        //validação do campo "Valor Final do Produto"
            String valorFinal = campoValorFinal.getText();

            valorFinal = valorFinal.replace(",", "");

            for(int i=0; i<valorFinal.length();i++)
                valorFinal = valorFinal.replace(" ", "");

        if(valorFinal.isEmpty()){
            msgErro = msgErro + "Diga o valor final do produto!\n";
            campoValorFinal.setForeground(Color.red);
        }else{
            Double valorFnl = Double.parseDouble(valorFinal);
            
            if( valorFnl == 0)
                msgErro = msgErro + "O valor final não pode ser 0!\n";
            else
                campoValorFinal.setForeground(new Color(46,0,71));
        }
        return msgErro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCadastrar1;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JTextField campoEspecifique;
    private javax.swing.JList<String> campoLista;
    private javax.swing.JTextField campoNomeProduto;
    private javax.swing.JFormattedTextField campoValorFinal;
    private javax.swing.JFormattedTextField campoValorMaterial;
    private javax.swing.ButtonGroup grupoCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel labelCabecalho;
    private javax.swing.JLabel labelEspecifique;
    private javax.swing.JLabel labelIcone;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelValorFinal;
    private javax.swing.JLabel labelValorMaterial;
    private javax.swing.JRadioButton opcaoBordado;
    private javax.swing.JRadioButton opcaoOutros;
    private javax.swing.JRadioButton opcaoPersonalizado;
    // End of variables declaration//GEN-END:variables
}
