/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;



import domain.Endereco;
import static funcoesUteis.ValidarCPF.isCPF;
import static funcoesUteis.ValidarTelefone.validarTelefone;
import funcoesUteis.WebServiceCep;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import task_manager.InterfaceManager;


/**
 *
 * @author gugag
 */
public class tela_cadastroCliente extends javax.swing.JDialog {

    private InterfaceManager ger;
    public tela_cadastroCliente(java.awt.Frame parent, boolean modal, InterfaceManager ger) {
        super(parent, modal);
        this.ger = ger;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        botaoCadastrar = new javax.swing.JButton();
        labelVoltar = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelBairro = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        labelLogradouro = new javax.swing.JLabel();
        campoLogradouro = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        campoCEP = new javax.swing.JFormattedTextField();
        labelCEP = new javax.swing.JLabel();
        campoNumeroCasa = new javax.swing.JTextField();
        campoCidade = new javax.swing.JTextField();
        labelLogradouro1 = new javax.swing.JLabel();
        labelLogradouro2 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        campoCPF = new javax.swing.JFormattedTextField();
        labelCPF = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelCliente = new javax.swing.JLabel();
        labelTEL = new javax.swing.JLabel();
        campoTEL = new javax.swing.JFormattedTextField();
        botaoFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpMain.setBackground(new java.awt.Color(46, 0, 71));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 255));
        jLabel25.setText("Cadastro de Cliente");

        jSeparator5.setBackground(new java.awt.Color(0, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 255, 255));

        botaoCadastrar.setBackground(new java.awt.Color(0, 255, 255));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(46, 0, 71));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        labelVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/icons8_logout_rounded_left_32px.png"))); // NOI18N
        labelVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVoltarMouseClicked(evt);
            }
        });

        labelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/perfil-de-usuario.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(46, 0, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 0, 255), 2, true), "Endereço", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));

        labelBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelBairro.setForeground(new java.awt.Color(147, 0, 255));
        labelBairro.setText("Bairro:");

        campoBairro.setForeground(new java.awt.Color(46, 0, 71));
        campoBairro.setDisabledTextColor(new java.awt.Color(46, 0, 71));
        campoBairro.setEnabled(false);

        labelLogradouro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelLogradouro.setForeground(new java.awt.Color(147, 0, 255));
        labelLogradouro.setText("Logradouro:");

        campoLogradouro.setForeground(new java.awt.Color(46, 0, 71));
        campoLogradouro.setDisabledTextColor(new java.awt.Color(46, 0, 71));
        campoLogradouro.setEnabled(false);

        labelNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(147, 0, 255));
        labelNumero.setText("Número:");

        campoCEP.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCEPFocusLost(evt);
            }
        });

        labelCEP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCEP.setForeground(new java.awt.Color(147, 0, 255));
        labelCEP.setText("CEP:");

        campoNumeroCasa.setForeground(new java.awt.Color(46, 0, 71));

        campoCidade.setForeground(new java.awt.Color(46, 0, 71));
        campoCidade.setDisabledTextColor(new java.awt.Color(46, 0, 71));
        campoCidade.setEnabled(false);

        labelLogradouro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelLogradouro1.setForeground(new java.awt.Color(147, 0, 255));
        labelLogradouro1.setText("Cidade:");

        labelLogradouro2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelLogradouro2.setForeground(new java.awt.Color(147, 0, 255));
        labelLogradouro2.setText("Estado:");

        campoEstado.setForeground(new java.awt.Color(46, 0, 71));
        campoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        campoEstado.setSelectedIndex(12);
        campoEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoEstado.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCEP)
                            .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBairro)
                            .addComponent(campoBairro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNumero)
                            .addComponent(labelLogradouro)
                            .addComponent(campoLogradouro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLogradouro1)
                                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEstado, 0, 233, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelLogradouro2)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogradouro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogradouro1)
                    .addComponent(labelLogradouro2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        jPanel2.setBackground(new java.awt.Color(46, 0, 71));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(147, 0, 255), 2, true), "Dados Pessoais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));

        campoCPF.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(147, 0, 255));
        labelCPF.setText("CPF:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        campoNome.setForeground(new java.awt.Color(46, 0, 71));

        labelCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(147, 0, 255));
        labelCliente.setText("Nome do Cliente:");

        labelTEL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTEL.setForeground(new java.awt.Color(147, 0, 255));
        labelTEL.setText("Número de Telefone:");

        campoTEL.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoTEL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoTEL, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(labelCliente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCPF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTEL, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCPF, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCliente)
                .addGap(6, 6, 6)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTEL)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(campoTEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoFoto.setBackground(new java.awt.Color(0, 255, 255));
        botaoFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoFoto.setForeground(new java.awt.Color(46, 0, 71));
        botaoFoto.setText("Carregar Foto");
        botaoFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(labelVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(238, 238, 238))
            .addComponent(jSeparator5)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpMainLayout.createSequentialGroup()
                        .addComponent(labelFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoFoto)
                        .addGap(15, 15, 15)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVoltarMouseClicked
        
        this.setVisible(false);
    }//GEN-LAST:event_labelVoltarMouseClicked

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        String msgErro = "";
        msgErro = validarCampos(msgErro);
        
        if(msgErro.isEmpty()){
            
            String nomeCliente = campoNome.getText();
            String cpf = campoCPF.getText();
            String telefone = campoTEL.getText();
            
            telefone = telefone.replace("(", "");
            telefone = telefone.replace(")", "");
            telefone = telefone.replace("-", "");
  
            String CEP = campoCEP.getText();
            
            CEP = CEP.replace("-", "");
            
            String bairro = campoBairro.getText();
            String logradouro = campoLogradouro.getText();
            String numeroCasa = campoNumeroCasa.getText();
            
            String cidade = campoCidade.getText();
            String estado = campoEstado.getSelectedItem().toString();
            
            //Enviar para o Banco
            
        }else{
            JOptionPane.showMessageDialog(this, msgErro, "Erro de Cadastro - Cliente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void campoCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCEPFocusLost
        
        String CEP = campoCEP.getText();
        CEP = CEP.replace("-", "");
        
        for(int i=0; i < CEP.length();i++)
            CEP = CEP.replace(" ", "");
            
        WebServiceCep cep = WebServiceCep.searchCep(campoCEP.getText());
        
        if(CEP.isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo CEP é obrigatório",
                    "Warning: CEP vazio", JOptionPane.WARNING_MESSAGE);
        }else{
            //caso a busca ocorra bem, imprime os resultados.
            if (cep.wasSuccessful()) {
                
                campoBairro.setEnabled(false);
                campoLogradouro.setEnabled(false);
                campoCidade.setEnabled(false);
                campoEstado.setEnabled(false);
                campoEstado.setCursor( new Cursor(0));
                
                campoLogradouro.setText(cep.getLogradouro());
                campoBairro.setText(cep.getBairro());
                campoCidade.setText(cep.getCidade());

                switch(cep.getUf()){

                    case "AC":
                        campoEstado.setSelectedItem("Acre");
                    break;

                    case "AL":
                        campoEstado.setSelectedItem("Alagoas");
                    break;

                    case "AP":
                        campoEstado.setSelectedItem("Amapá");
                    break;

                    case "AM":
                        campoEstado.setSelectedItem("Amazonas");
                    break;

                    case "BA":
                        campoEstado.setSelectedItem("Bahia");
                    break;

                    case "CE":
                        campoEstado.setSelectedItem("Ceará");
                    break;

                    case "ES":
                        campoEstado.setSelectedItem("Espírito Santo");
                    break;

                    case "GO":
                        campoEstado.setSelectedItem("Goiás");
                    break;

                    case "MA":
                        campoEstado.setSelectedItem("Maranhão");
                    break;

                    case "MT":
                        campoEstado.setSelectedItem("Mato Grosso");
                    break;

                    case "MS":
                        campoEstado.setSelectedItem("Mato Grosso do Sul");
                    break;

                    case "MG":
                        campoEstado.setSelectedItem("Minas Gerais");
                    break;

                    case "PA":
                        campoEstado.setSelectedItem("Pará");
                    break;

                    case "PB":
                        campoEstado.setSelectedItem("Paraíba");
                    break;

                    case "PR":
                        campoEstado.setSelectedItem("Paraná");
                    break;

                    case "PE":
                        campoEstado.setSelectedItem("Pernambuco");
                    break;

                    case "PI":
                        campoEstado.setSelectedItem("Piauí");
                    break;

                    case "RJ":
                        campoEstado.setSelectedItem("Rio de Janeiro");
                    break;

                    case "RN":
                        campoEstado.setSelectedItem("Rio Grande do Norte");
                    break;

                    case "RS":
                        campoEstado.setSelectedItem("Rio Grande do Sul");
                    break;

                    case "RO":
                        campoEstado.setSelectedItem("Rondônia");
                    break;

                    case "RR":
                        campoEstado.setSelectedItem("Roraima");
                    break;

                    case "SC":
                        campoEstado.setSelectedItem("Santa Catarina");
                    break;

                    case "SP":
                        campoEstado.setSelectedItem("São Paulo");
                    break;

                    case "SE":
                        campoEstado.setSelectedItem("Sergipe");
                    break;

                    case "TO":
                        campoEstado.setSelectedItem("Tocantins");
                    break;

                    default:
                        campoEstado.setSelectedItem("Distrito Federal");
                    break;    
                }
            //caso haja problemas imprime o código e msg de erro.
            }else {

                JOptionPane.showMessageDialog(this, "CEP não encontrado, digite seu endereço manualmente!\n"
                        + "Ou tente novamente...",
                        "Erro: CEP não encontrado", JOptionPane.ERROR_MESSAGE);
                campoBairro.setEnabled(true);
                campoLogradouro.setEnabled(true);
                campoCidade.setEnabled(true);
                campoEstado.setEnabled(true);
                campoEstado.setCursor( new Cursor(12));

            }
        }
        
        
    }//GEN-LAST:event_campoCEPFocusLost

    private void botaoFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFotoActionPerformed
        
        
        JOptionPane.showMessageDialog(this, "Não é possível carregar a foto!\n"
                        + "Preciso consertar essa porra...",
                        "Erro: Foto não carregada", JOptionPane.ERROR_MESSAGE);
//        JFileChooser janArq = new JFileChooser();
//        
//        janArq.setAcceptAllFileFilterUsed(false);
//        janArq.setFileFilter( new FileNameExtensionFilter("Arquivos de imagem", "jpg", "png", "gif", "bmp") );
//        janArq.addChoosableFileFilter( new FileNameExtensionFilter("Arquivos de texto", "txt", "doc", "docx") );
//        
//        if ( janArq.showOpenDialog(this) == JFileChooser.APPROVE_OPTION  ) {
//            File arquivo = janArq.getSelectedFile();
//            Icon imagem = new ImageIcon( arquivo.getAbsolutePath() );
//            
//            labelFoto.setText("");                
//            labelFoto.setIcon(imagem);
//            //mostrarFoto(imagem);
//        }
    }//GEN-LAST:event_botaoFotoActionPerformed

    public String validarCampos(String msgErro){
        
        if(campoNome.getText().isEmpty()){
            msgErro = msgErro + "Nome inválido!\n";
            campoNome.setForeground(Color.red);
            campoNome.setText("");
        }else
            campoNome.setForeground(new Color(46,0,71));
        
        if(!isCPF(campoCPF.getText())){
            msgErro = msgErro + "CPF inválido!\n";
            campoCPF.setForeground(Color.red);
        }else
            campoCPF.setForeground(new Color(46,0,71));
        
        if(!validarTelefone(campoTEL.getText())){
            msgErro = msgErro + "Telefone inválido!\n";
            campoTEL.setForeground(Color.red);
        }else
            campoTEL.setForeground(new Color(46,0,71));
        
        if(campoCEP.getText().isEmpty() || campoCEP.getText().length() != 8){
            msgErro = msgErro + "CEP inválido!\n";
            campoCEP.setForeground(Color.red);
        }else
            campoCEP.setForeground(new Color(46,0,71));
        
        if(campoBairro.getText().isEmpty() || campoLogradouro.getText().isEmpty() || campoCidade.getText().isEmpty()){
            msgErro = msgErro + "Endereço inválido! (Pesquise seu CEP)\n";
        }else
            campoCEP.setForeground(new Color(46,0,71));
        
        if(campoNumeroCasa.getText().isEmpty()){
            msgErro = msgErro + "Número residencial inválido!\n";
            campoNumeroCasa.setForeground(Color.red);
        }else
            campoNumeroCasa.setForeground(new Color(46,0,71));
        
        return msgErro;
    }
    
    private void mostrarFoto(Icon imagem) {
        // Redimensionar
        ImageIcon imagem2 = (ImageIcon) new ImageIcon();
        imagem2.setImage(imagem2.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_DEFAULT));
        
        labelFoto.setText("");                
        labelFoto.setIcon(imagem);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoFoto;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JFormattedTextField campoCEP;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JComboBox<String> campoEstado;
    private javax.swing.JTextField campoLogradouro;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumeroCasa;
    private javax.swing.JFormattedTextField campoTEL;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelLogradouro;
    private javax.swing.JLabel labelLogradouro1;
    private javax.swing.JLabel labelLogradouro2;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelTEL;
    private javax.swing.JLabel labelVoltar;
    // End of variables declaration//GEN-END:variables

}
