/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import domain.Administrador;
import javax.swing.JDialog;
import javax.swing.JFrame;
import task_manager.InterfaceManager;


/**
 *
 * @author gugag
 */
public class tela_login extends javax.swing.JDialog {

    private InterfaceManager ger;
    
    public tela_login(java.awt.Frame parent, boolean modal, InterfaceManager ger) {
        super(parent, modal);
        this.ger = ger;
        initComponents();
        
        LabelErro.setVisible(false);
    }

    private tela_login(JFrame jFrame, boolean b) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BotaoCadastrarSenha = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LabelErro = new javax.swing.JLabel();
        PasswordSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 70));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(46, 0, 71));
        jPanel1.setMinimumSize(new java.awt.Dimension(552, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(498, 582));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Entrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(46, 0, 71));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/user.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(1, 206, 220));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 0, 71));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Esqueceu a senha?");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        BotaoCadastrarSenha.setBackground(new java.awt.Color(0, 255, 255));
        BotaoCadastrarSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoCadastrarSenha.setForeground(new java.awt.Color(0, 0, 0));
        BotaoCadastrarSenha.setText("Cadastrar nova senha");
        BotaoCadastrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarSenhaActionPerformed(evt);
            }
        });
        jPanel3.add(BotaoCadastrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 167, 260, -1));

        jLabel5.setBackground(new java.awt.Color(1, 206, 220));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Senha:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        TextUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TextUsuario.setForeground(new java.awt.Color(46, 0, 71));
        TextUsuario.setText("Admin");
        TextUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 410, 31));

        jLabel3.setBackground(new java.awt.Color(1, 206, 220));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Usuário:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, -1));

        LabelErro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelErro.setForeground(new java.awt.Color(255, 0, 0));
        LabelErro.setText("Usuario ou senha incorreto(os)!");
        jPanel3.add(LabelErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        PasswordSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordSenha.setForeground(new java.awt.Color(46, 0, 71));
        PasswordSenha.setText("adm123");
        jPanel3.add(PasswordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 121, 410, 31));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Administrador adm = new Administrador();
        String usuario = TextUsuario.getText();
        String senha = PasswordSenha.getText();

        
        if(usuario.equals(adm.getUserID()) && senha.equals(adm.getSenha())){
            ger.abrirTelaPrincipal(ger);
            this.setVisible(false);
            LabelErro.setVisible(false);
        }else{
            TextUsuario.setText("");
            PasswordSenha.setText("");
            LabelErro.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotaoCadastrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarSenhaActionPerformed
        
        ger.abrirTelaCadastrarSenha();
    }//GEN-LAST:event_BotaoCadastrarSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarSenha;
    private javax.swing.JLabel LabelErro;
    private javax.swing.JPasswordField PasswordSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
