/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import static funcoesUteis.FuncoesDate.strToDate;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import task_manager.InterfaceManager;

/**
 *
 * @author gugag
 */
public class tela_cadastroMaterial extends javax.swing.JDialog {

    private InterfaceManager ger;

    private tela_cadastroMaterial(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public InterfaceManager getGer(){
        return this.ger;
    }
    
    public tela_cadastroMaterial(java.awt.Frame parent, boolean modal, InterfaceManager ger) {
        super(parent, modal);
        this.ger = ger;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoQnt = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        campoData = new javax.swing.JFormattedTextField();
        campoValor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoFornecedor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpMain.setBackground(new java.awt.Color(46, 0, 71));
        jpMain.setForeground(new java.awt.Color(0, 255, 255));
        jpMain.setEnabled(false);
        jpMain.setName("card1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Nome do Material:");

        campoNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        campoNome.setForeground(new java.awt.Color(46, 0, 71));

        campoTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        campoTipo.setForeground(new java.awt.Color(46, 0, 71));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Tipo do Material:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Quantidade do Material:");

        campoQnt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        campoQnt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        campoQnt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Data de Compra:");

        campoData.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });

        campoValor.setForeground(new java.awt.Color(46, 0, 71));
        try {
            campoValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Valor unitário do Material:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Nome do Fornecedor:");

        campoFornecedor.setForeground(new java.awt.Color(46, 0, 71));

        jSeparator1.setBackground(new java.awt.Color(0, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(46, 0, 71));
        jButton1.setText("Cadastrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 255));
        jLabel25.setText("Cadastro de Material");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windows/imagens/icons8_logout_rounded_left_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(46, 0, 71));
        jButton2.setText("Limpar Campos");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel5))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(campoQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25))
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataActionPerformed

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String msgErro = "";
        msgErro = validarCampos(msgErro);

        if(msgErro.isEmpty()){
            
            String nomeMaterial = campoNome.getText();
            String tipoMaterial = campoTipo.getText();
            String data = campoData.getText();
            int quantidade = Integer.parseInt(campoQnt.getValue().toString());
            String valorMaterial = campoValor.getText();
            String fornecedor = campoFornecedor.getText();
            
        }else
        JOptionPane.showMessageDialog(this, msgErro, "Erro de Cadastro - Cliente", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        campoNome.setText("");
        campoTipo.setText("");
        campoData.setText("");
        campoQnt.setValue(0);
        campoValor.setText("");
        campoFornecedor.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    public String validarCampos(String msgErro){
        
        if(campoNome.getText().isEmpty()){
            msgErro = msgErro + "Nome inválido!\n";
            campoNome.setForeground(Color.red);
            campoNome.setText("");
        }else
            campoNome.setForeground(new Color(46,0,71));
        
        if(campoTipo.getText().isEmpty()){
            msgErro = msgErro + "Tipo inválido!\n";
            campoTipo.setForeground(Color.red);
            campoTipo.setText("");
        }else
            campoTipo.setForeground(new Color(46,0,71));
        
        if(campoFornecedor.getText().isEmpty()){
            msgErro = msgErro + "Fornecedor inválido!\n";
            campoFornecedor.setForeground(Color.red);
            campoFornecedor.setText("");
        }else
            campoFornecedor.setForeground(new Color(46,0,71));
        
        int quantidade = Integer.parseInt(campoQnt.getValue().toString());
        
        if(quantidade == 0){
            msgErro = msgErro + "Quantidade inválido!\n"
                    + "Quantidade não pode ser 0\n";
            campoQnt.setForeground(Color.red);
        
        }else
            campoQnt.setForeground(new Color(46,0,71));
        
        //validação do campo "Valor Final do Produto"
            String valorMaterial = campoValor.getText();

            valorMaterial = valorMaterial.replace(",", "");

            for(int i=0; i<valorMaterial.length();i++)
                valorMaterial = valorMaterial.replace(" ", "");

        if(valorMaterial.isEmpty()){
            msgErro = msgErro + "Diga o valor do material!\n";
            campoValor.setForeground(Color.red);
        }else{
            Double valorFnl = Double.parseDouble(valorMaterial);
            
            if( valorFnl == 0)
                msgErro = msgErro + "O valor não pode ser 0!\n";
            else
                campoValor.setForeground(new Color(46,0,71));
        }
        
        
        
        try {
            
            //Preciso transformar isso em exceção
            
                String dataLida = campoData.getText();

                dataLida = dataLida.replace("/", "");
                dataLida = dataLida.replace("/", "");
                
                for(int i=0;i<dataLida.length();i++)
                    dataLida = dataLida.replace(" ", "");
                
                if(dataLida.isEmpty()){
                    msgErro = msgErro + "Data vazia.\n";
                    campoData.setForeground(Color.red);
                }else{
                    

                    int contador = 0, indiceAtual=0, indiceAnterior=0;

                    for(int i=0;i<dataLida.length();i++){

                        char ind = dataLida.charAt(i);
                        if(i > 0){
                            if(ind == dataLida.charAt(i-1))
                                contador++;
                        }

                        if(i==5){
                                indiceAtual = Character.digit(dataLida.charAt(i), 10);
                                indiceAnterior = Character.digit(dataLida.charAt(i - 1), 10);
                                if (indiceAnterior <= 1 && indiceAtual >= 9) {
                                    msgErro = msgErro + "Data inválida.\n"
                                            + "Não aceita-se anos anteriores aos anos 2000.\n";
                                    campoData.setForeground(Color.red);
                                }
                        }    

                    }

                    if(contador >= 5){
                        msgErro = msgErro + "Data com excesso de Números repetidos.\n";
                        campoData.setForeground(Color.red);
                    }
                }
            //=================================================
            
            Date data = strToDate(campoData.getText());
        }
        catch (ParseException ex) {
            msgErro = msgErro + "Data inválida.\n";
            campoData.setForeground(Color.red); 
        }
        catch (Exception erro) {
            msgErro = msgErro + erro.getMessage() + "\n";
            campoData.setForeground(Color.red); 
        }

        return msgErro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextField campoFornecedor;
    private javax.swing.JTextField campoNome;
    private javax.swing.JSpinner campoQnt;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JFormattedTextField campoValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpMain;
    // End of variables declaration//GEN-END:variables
}
